### ISSUE TITLE
Does not add default cluster

### ISSUE THREAD

**Issue by AceHack** [MacTynow/kafka-manager-chart#4]
Running with the following values:

```
kafka:
  clusters:
    - name: "platform"
      zkHosts: "platform-zookeeper:2181"
      kafkaVersion: "0.9.1"

kafkaManager:
  useKafkaZookeeper: true
  zkHosts: ""
```

I end up with no clusters configured
